#!/bin/bash

# =============================================================================
# Impact Blast Radius Scanner
# 
# Usage:
#   ./impact-scan.sh <ClassName or FileName> [project_root]
#
# Examples:
#   ./impact-scan.sh PayeeValidator
#   ./impact-scan.sh PayeeValidator ~/projects/active/ADO-123456-login
#   ./impact-scan.sh "PayeeValidator\|PayeeModel"   # multiple classes
#
# Output:
#   Generates impact-report-{class}-{date}.md in current directory
# =============================================================================

set -e

TARGET="${1:?Usage: ./impact-scan.sh <ClassName> [project_root]}"
PROJECT_ROOT="${2:-.}"
DATE=$(date +%Y-%m-%d)
SAFE_TARGET=$(echo "$TARGET" | sed 's/\\|/_/g')
REPORT="impact-report-${SAFE_TARGET}-${DATE}.md"

echo "🔍 Scanning impact for: $TARGET"
echo "📁 Project root: $PROJECT_ROOT"
echo "📄 Report: $REPORT"
echo ""

# --- Helper ---
count_hits() {
    local pattern="$1"
    local label="$2"
    local count
    count=$(grep -rn "$pattern" --include="*.swift" "$PROJECT_ROOT" 2>/dev/null | grep -v "Test" | grep -v "Mock" | grep -v ".build/" | wc -l | tr -d ' ')
    echo "$count"
}

# --- Start Report ---
cat > "$REPORT" <<EOF
# Impact Blast Radius Report

- **Target**: \`$TARGET\`
- **Project**: \`$PROJECT_ROOT\`
- **Date**: $DATE
- **Generated by**: impact-scan.sh

---

## Quick Summary

EOF

TOTAL=$(count_hits "$TARGET" "total")
echo "| Metric | Count |" >> "$REPORT"
echo "|--------|-------|" >> "$REPORT"
echo "| Total references (excl. Test/Mock) | $TOTAL |" >> "$REPORT"

if [ "$TOTAL" -lt 5 ]; then
    echo "| Blast radius | 🟢 Low |" >> "$REPORT"
elif [ "$TOTAL" -lt 15 ]; then
    echo "| Blast radius | 🟡 Medium |" >> "$REPORT"
else
    echo "| Blast radius | 🔴 High — shared core component |" >> "$REPORT"
fi

echo "" >> "$REPORT"

# --- Section 1: All references ---
echo "---" >> "$REPORT"
echo "" >> "$REPORT"
echo "## 1. All References (excluding Test / Mock)" >> "$REPORT"
echo "" >> "$REPORT"
echo '```' >> "$REPORT"
grep -rn "$TARGET" --include="*.swift" "$PROJECT_ROOT" 2>/dev/null | grep -v "Test" | grep -v "Mock" | grep -v ".build/" | sort >> "$REPORT" 2>/dev/null || echo "(no results)" >> "$REPORT"
echo '```' >> "$REPORT"
echo "" >> "$REPORT"

# --- Section 2: Import statements ---
echo "---" >> "$REPORT"
echo "" >> "$REPORT"
echo "## 2. Files That Import This" >> "$REPORT"
echo "" >> "$REPORT"
echo '```' >> "$REPORT"
grep -rn "import.*$TARGET" --include="*.swift" "$PROJECT_ROOT" 2>/dev/null | grep -v "Test" | grep -v "Mock" | grep -v ".build/" | sort >> "$REPORT" 2>/dev/null || echo "(no import statements found — may use @testable or same module)" >> "$REPORT"
echo '```' >> "$REPORT"
echo "" >> "$REPORT"

# --- Section 3: Group by directory / module ---
echo "---" >> "$REPORT"
echo "" >> "$REPORT"
echo "## 3. Affected Modules / Directories" >> "$REPORT"
echo "" >> "$REPORT"
echo "| Directory | File Count | Files |" >> "$REPORT"
echo "|-----------|:----------:|-------|" >> "$REPORT"

grep -rln "$TARGET" --include="*.swift" "$PROJECT_ROOT" 2>/dev/null | grep -v "Test" | grep -v "Mock" | grep -v ".build/" | while read -r file; do
    dirname "$file"
done | sort | uniq -c | sort -rn | while read -r count dir; do
    files=$(grep -rln "$TARGET" --include="*.swift" "$dir" 2>/dev/null | grep -v "Test" | grep -v "Mock" | grep -v ".build/" | xargs -I{} basename {} | sort | tr '\n' ', ' | sed 's/,$//')
    echo "| \`$dir\` | $count | $files |" >> "$REPORT"
done

echo "" >> "$REPORT"

# --- Section 4: ViewControllers / Views that reference this ---
echo "---" >> "$REPORT"
echo "" >> "$REPORT"
echo "## 4. UI Layer References (ViewControllers / Views / Coordinators)" >> "$REPORT"
echo "" >> "$REPORT"
echo "These are the entry points — they map to user-facing screens and flows." >> "$REPORT"
echo "" >> "$REPORT"
echo '```' >> "$REPORT"
grep -rln "$TARGET" --include="*.swift" "$PROJECT_ROOT" 2>/dev/null | grep -v "Test" | grep -v "Mock" | grep -v ".build/" | xargs grep -l "ViewController\|View\|Coordinator\|Screen\|Router" 2>/dev/null | sort | uniq >> "$REPORT" 2>/dev/null || echo "(no UI layer files found)" >> "$REPORT"
echo '```' >> "$REPORT"
echo "" >> "$REPORT"

# --- Section 5: Country-specific references ---
echo "---" >> "$REPORT"
echo "" >> "$REPORT"
echo "## 5. Country-Specific Code Near References" >> "$REPORT"
echo "" >> "$REPORT"
echo "Lines that mention both \`$TARGET\` AND a country code pattern nearby:" >> "$REPORT"
echo "" >> "$REPORT"
echo '```' >> "$REPORT"

# Get files that reference target, then search those files for country patterns
grep -rln "$TARGET" --include="*.swift" "$PROJECT_ROOT" 2>/dev/null | grep -v "Test" | grep -v "Mock" | grep -v ".build/" | while read -r file; do
    country_hits=$(grep -n "countryCode\|\"HK\"\|\"SG\"\|\"US\"\|\"MY\"\|\"TH\"\|\"IN\"\|\"CN\"\|\"TW\"\|country ==" "$file" 2>/dev/null)
    if [ -n "$country_hits" ]; then
        echo "--- $file ---"
        echo "$country_hits"
        echo ""
    fi
done >> "$REPORT" 2>/dev/null

echo '```' >> "$REPORT"
echo "" >> "$REPORT"

# --- Section 6: Protocol conformance ---
echo "---" >> "$REPORT"
echo "" >> "$REPORT"
echo "## 6. Protocol / Inheritance Chain" >> "$REPORT"
echo "" >> "$REPORT"
echo "If \`$TARGET\` is used via protocol, grep may miss some callers. Check these:" >> "$REPORT"
echo "" >> "$REPORT"
echo '```' >> "$REPORT"
grep -rn "protocol.*$TARGET\|: $TARGET\|: .*$TARGET" --include="*.swift" "$PROJECT_ROOT" 2>/dev/null | grep -v "Test" | grep -v "Mock" | grep -v ".build/" | sort >> "$REPORT" 2>/dev/null || echo "(no protocol/inheritance found)" >> "$REPORT"
echo '```' >> "$REPORT"
echo "" >> "$REPORT"

# --- Section 7: Action items template ---
cat >> "$REPORT" <<'EOF'
---

## 7. Action Items (fill in manually)

### Spot-Read Checklist

| File | Line | What It Does | My Change Affects? | Notes |
|------|------|-------------|:------------------:|-------|
| | | | | |
| | | | | |

### Impact Confidence After Review

| Area / Flow | Confidence | Evidence | RT Needed? |
|-------------|:----------:|----------|:----------:|
| | 🟢 / 🟡 / 🔴 | | |
| | 🟢 / 🟡 / 🔴 | | |

### RT Recommendation

| Priority | Test Case | Flow | Why |
|----------|-----------|------|-----|
| 🔴 P0 | | | |
| 🟡 P1 | | | |
| 🟢 P2 | | | |

### Risk Flags

| Risk | Flagged To | Date | Evidence Link |
|------|-----------|------|---------------|
| | | | |
EOF

echo ""
echo "✅ Report generated: $REPORT"
echo ""
echo "📊 Quick summary:"
echo "   Total references: $TOTAL"
if [ "$TOTAL" -lt 5 ]; then
    echo "   Blast radius: 🟢 Low"
elif [ "$TOTAL" -lt 15 ]; then
    echo "   Blast radius: 🟡 Medium"
else
    echo "   Blast radius: 🔴 High — this is a shared core component, flag broadly"
fi
echo ""
echo "📋 Next steps:"
echo "   1. Open $REPORT"
echo "   2. Review Section 4 (UI layer) — these are the affected screens"
echo "   3. Review Section 5 (country-specific) — check cross-country impact"
echo "   4. Spot-read the key lines (Section 7 template)"
echo "   5. Fill in RT recommendation and send to QA"